# Generated by Django 2.1.4 on 2019-02-07 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.IntegerField(unique=True, verbose_name='Grade')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=1, verbose_name='Room')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Grade', verbose_name='Grade')),
            ],
        ),
        migrations.CreateModel(
            name='Semister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semister', models.CharField(choices=[('1', 'First'), ('2', 'Second')], default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Room', verbose_name='Room')),
                ('s', models.ForeignKey(limit_choices_to={'role__r_name': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=100, verbose_name='Subject')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Grade', verbose_name='Grade')),
            ],
        ),
        migrations.CreateModel(
            name='Teach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semisterID', models.IntegerField(verbose_name='Semister')),
                ('roomID', models.ManyToManyField(to='staff.Room', verbose_name='Room')),
                ('subjectID', models.ManyToManyField(to='staff.Subject', verbose_name='Subject')),
                ('teacherID', models.ForeignKey(limit_choices_to={'role__r_name': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Teacher')),
            ],
            options={
                'verbose_name_plural': 'teach',
            },
        ),
    ]
