XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXX XXX XXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXX
        XXX XXX X XXXXXXXX XXXXXX X
            XXXXXXX X XXXXXXX XX XXX
            XXXXXXXXXXXXXXXXXXX
        XX
        XXXXXXXXXXXXX X XXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX
        XX
    XXXXXXXXX
    XXXXXXXX
        XXX XXX XXX XXX XXX

        XX XXXXXXX XX XXXXXXXXX
        XXXXXXXXXXXXX XX X XXXXXXXX XX X
            XXXXX   XXX XXXXXXX
        XXX
        XXXXXXXXXXXXXXXXXX XX X XXXXXXXX XX X
            XXXXX   XXX XX XXXXXXXX
        XXX
        XXXXXXXXXXXXXXXXXXX XX X XXXXXXXX XX X
            XXXXX   XXX XX XXXXXXXXX
        XXX
        XXXXXXXXXXXXXXXXXXX XX X XXXXXXXX XX X
            XXXXX   XXXXXXXX
        XXX
        XXXXXXXXXXXXXXX XXXXXXXX XX X
            XXXXX   XXX XXXXXXXXXXXXX
        XXXXXXX
        
        XX XXXX XXXXXX
        XXXXXXX XXXX XXXXXXXX
        XXXXXXXXXXXXXXXX
        XX XXX XXXX
        XX XXX XX XXXXX
        XXXXXXXXX XXXXXXXX
        XX XXX XXX XXX XXX XX XXX XX XXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXX
        XX XXX XXXX
        XX XXX XX XXXXXX
        XX XXXXX

        XX XXXXXXXXX
        XXXXXXXX
        XXXXXXXXXXXXXXXXX XXXX
        XXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXX
        XX XXX XXXX
        XX XXXXX

        XX XXXXXXXXX XX XXXXXXXX
        XXXXXXXX
        XXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXX XXXXXXXX
        XXXXXXXXXXXXXXXX
        XX XXX XXXX
        XXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXX
        XX XXX XXXX
    XXXXXXXXX
    XXXX XXXXXXXXXXXXXXX
XXXXXXX
