XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
    XX XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
    XX XXXXXXXXXXXXXXX XXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
XXXXXX

XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXX XXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXXXXXXX
    XXX

    XXX XXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXXXXXXX
    XXX

XX XXXXXXX
XXXXXXXXX

XXXXXXX
    XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX X
        XXXXXX XXXXXX
    X
    XXXXXXXXXXXXXXXX X
        XXXXXXX XXXXXX
    X
XXXXXXXX
