XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXX XXXXXX
                XX XXXXXXXXXXXXXXX XXX XXXXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXX XXXXXX XXXXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX


XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X X XXX

    XXXXXXXXXXXXXXXXXXXXX X
        XXX XXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXX
        XXX
    XX XXXXXX
XX XXXXXXX
XXXXXXXXX

XXXXXXX
    XXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXX
        XXXXXXX XXXXXX
        XXXXX XX
    X
    XXXXXXXXXXXXXXXXXXXX X
        XXXXXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXXXXX
    X
XXXXXXXX
