XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXX XXXXXX
    XX XXXXXXXXXXXXXXX XXX XXXXXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXX XXXXX XXXXX XX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
XXXXXX

XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXX
        XXXXXXXXXX X
            XXXXX X
                XXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXX
            XX
            XXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX
        X
    XXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX X
            XXXXXXXXXXXX XXXXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXX X XXXX XX XXXXX XX XXXXXXX XX XXXXXX X X
        XX
        XXXXXXX XXXXXXXXXXXXXXXX
    XXX
    XXX X X XX X X XX
    XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX X
        XXXXXX X XXXXXXXXXXXXX
            XX XXXX XXX XXXXXXX XXXXXXXX XX XXX XXXXXXXXXXXXX XXXXXXXXXX
            X XX XXXXXXXXX
            X XX XXXXXXXXX

        XX XXXXXXXXX XXX XXXXXXX
        XXXXXXXXXXXXXXXX X X X XXXXX
        XXXXXXXXXXXXXXXXX X X X XXXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X

XX XXXXXXX
XXXXXXXXX

XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    X
XXXXXXXX
