XXXX XXXXXX XXX
XXXXXXX XXXXXXXXXXXX
  XXX XXXXXXXXXXXXXX
    BBB BBBBBB BB BBBBBBBBBBB
    BB BBBBBBBBB
    BB BBBBBBBBB BB BBBBBBB
    XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
           XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBB
    XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXX
           XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBB
    BBBBB
    BBBBBB
  XXXXX
  XXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXX BBBBBB BBBBBBBB B BBBBBBBBB B BBBBB BBBB
    BB BBBBBBBBBBBBBBBBBBBB
      BBBBBBB BBBB FFFFFFFFFFFFFFBBBBBBBBBB
      BB BBBB BBBBBBBB BBBXBBBBB
    BBBBB
    
    BB BBBBBBBBBBBBBBBBBBBXXXXX
    XXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXXX XXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX
XXXXXXXXX
